# Generated by Django 5.2.17 on 2026-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=500)),
                ('notes', models.TextField(blank=True, help_text='You can add your personal notes about this character here.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
